sudo: required
dist: trusty
language: cpp
compiler:
    - clang++
script:
    - autoconf
    - ./configure
    - make
install:
    - sudo apt-get -qq update
    - sudo apt-get -qq --force-yes install llvm clang libclang-dev
