sudo: required
dist: trusty
language: cpp
compiler:
    - clang++
script:
    - ./autogen.sh
    - make
    - make check
install:
    - sudo apt-get -qq update
    - sudo apt-get -qq --force-yes install llvm clang libclang-dev libcppunit-dev
