sudo: false
language: cpp
compiler:
    - clang++
before_install:
    - export PATH=/usr/lib/llvm-3.7/bin:$PATH
script:
    - ./autogen.sh --enable-werror --enable-debug
    - make
    - make check
addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
        packages:
            - llvm-3.7
            - clang-3.7
            - libclang-3.7-dev
            - libcppunit-dev
