sudo: false
language: cpp
compiler:
    - clang++
script:
    - ./autogen.sh --enable-werror
    - make
    - make check
addons:
    apt:
        packages:
            - llvm
            - clang
            - libcppunit-dev
